[package]
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]
build = "build.rs"
name = "iron_llvm"
version = "0.0.1"

[build-dependencies]
cmake = "0.1.12"

[dependencies]
libc = "0.2.10"
llvm-sys = "0.3.0"
